### ISSUE TITLE
Using default tag: latest Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

### ISSUE THREAD

**Issue by My12123** [soruly/trace.moe-media#114]
Using default tag: latest
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
![2022-12-28_11-17-01](https://user-images.githubusercontent.com/49092250/209780977-d2d91bf9-ea61-43c1-afdd-aac93f25766f.png)

**Comment by soruly** [comment]
I think this is an issue on your docker.
Try pulling some other images not created by me.
If the issue still exists, it means it's your docker's issue instead of my docker image.
Sorry I cannot help everyone hand by hand to debug issues not related to my own code.
